# Generated by Django 6.1 on 2026-09-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Картой онлайн'), ('cash', 'Наличными при получении')], max_length=20, verbose_name='способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен')], default='pending', max_length=20, verbose_name='статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='оплачен')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
