# Generated by Django 6.1 on 2026-08-25 12:26

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона в формате +77001234567', regex='^\\+7\\d{10}$')], verbose_name='телефон')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts_user_set', to='auth.group', verbose_name='группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts_user_set', to='auth.permission', verbose_name='права доступа')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house', models.CharField(max_length=20, verbose_name='дом')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='квартира/офис')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='индекс')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='комментарий курьеру')),
                ('is_default', models.BooleanField(default=False, verbose_name='адрес по умолчанию')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'адрес доставки',
                'verbose_name_plural': 'адреса доставки',
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='user_has_email_or_phone'),
        ),
    ]
