# Generated by Django 6.1 on 2026-09-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='файл')),
                ('status', models.CharField(choices=[('uploaded', 'Файл загружен'), ('mapped', 'Колонки сопоставлены'), ('images_pending', 'Ожидает картинок'), ('pending_approval', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='uploaded', max_length=20, verbose_name='статус')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='сопоставление колонок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='когда проверено')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='причина отклонения')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'импорт каталога',
                'verbose_name_plural': 'импорты каталога',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='номер строки')),
                ('raw_data', models.JSONField(default=dict, verbose_name='данные строки')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='ошибка')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='bulk_import.importbatch', verbose_name='импорт')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='products.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'строка импорта',
                'verbose_name_plural': 'строки импорта',
                'ordering': ['row_number'],
            },
        ),
    ]
